# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4800df753bacd3eacc930e92fedefbcfaef876e9ea86687134600000f621eb556cb423813435c324e3567c063c737c6154bf4c2b162885a1a0573749605c7a8

test:
  secret_key_base: 382a90e29a9205bedc1887efcb0c30280534ed173af67707f51a9bbabfee99d66e1867572894378f9499c4bfc1739363f7875a25606e42e09b0db26e36659cfa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
